const menuItems = [
  {
    itemId: "margherita",
    category: "classic",
    name: "Margherita",
    description: "San Marzano tomato sauce, fresh mozzarella, basil, extra virgin olive oil",
    price: 14,
    badges: ["Popular", "Vegetarian"],
  },
  {
    itemId: "pepperoni",
    category: "classic",
    name: "Pepperoni",
    description: "Tomato sauce, mozzarella, spicy pepperoni, oregano",
    price: 16,
    badges: ["Popular"],
  },
  {
    itemId: "quattro-formaggi",
    category: "classic",
    name: "Quattro Formaggi",
    description: "Mozzarella, gorgonzola, parmesan, fontina cheese blend",
    price: 17,
    badges: ["Vegetarian"],
  },
  {
    itemId: "marinara",
    category: "classic",
    name: "Marinara",
    description: "San Marzano tomatoes, garlic, oregano, extra virgin olive oil - no cheese",
    price: 12,
    badges: ["Vegetarian"],
  },
  {
    itemId: "capricciosa",
    category: "classic",
    name: "Capricciosa",
    description: "Tomato, mozzarella, ham, mushrooms, artichokes, olives",
    price: 18,
    badges: [],
  },
  {
    itemId: "truffle-mushroom",
    category: "specialty",
    name: "Truffle Mushroom",
    description: "Wild mushroom medley, truffle cream, mozzarella, arugula, shaved parmesan",
    price: 22,
    badges: ["Popular", "Vegetarian"],
  },
  {
    itemId: "prosciutto-rucola",
    category: "specialty",
    name: "Prosciutto e Rucola",
    description: "Tomato, mozzarella, Prosciutto di Parma, arugula, parmesan shavings",
    price: 20,
    badges: [],
  },
  {
    itemId: "diavola",
    category: "specialty",
    name: "Diavola",
    description: "Spicy salami, roasted peppers, tomato sauce, mozzarella, chili flakes",
    price: 18,
    badges: [],
  },
  {
    itemId: "bbq-chicken",
    category: "specialty",
    name: "BBQ Chicken",
    description: "Grilled chicken, BBQ sauce, red onion, cilantro, smoked gouda",
    price: 19,
    badges: [],
  },
  {
    itemId: "mediterranean",
    category: "specialty",
    name: "Mediterranean",
    description: "Sun-dried tomatoes, olives, feta, artichokes, roasted peppers, pesto drizzle",
    price: 19,
    badges: ["Vegetarian"],
  },
  {
    itemId: "bruschetta-trio",
    category: "starters",
    name: "Bruschetta Trio",
    description: "Classic tomato-basil, mushroom truffle, and ricotta-honey on toasted ciabatta",
    price: 12,
    badges: [],
  },
  {
    itemId: "caprese-salad",
    category: "starters",
    name: "Caprese Salad",
    description: "Fresh buffalo mozzarella, vine tomatoes, basil, balsamic reduction",
    price: 13,
    badges: ["Vegetarian"],
  },
  {
    itemId: "arancini",
    category: "starters",
    name: "Arancini",
    description: "Crispy risotto balls filled with mozzarella, served with marinara",
    price: 11,
    badges: [],
  },
  {
    itemId: "caesar-salad",
    category: "starters",
    name: "Caesar Salad",
    description: "Romaine hearts, house-made caesar dressing, croutons, parmesan",
    price: 11,
    badges: [],
  },
  {
    itemId: "tiramisu",
    category: "desserts",
    name: "Tiramisu",
    description: "Classic espresso-soaked ladyfingers with mascarpone cream",
    price: 10,
    badges: ["Popular"],
  },
  {
    itemId: "panna-cotta",
    category: "desserts",
    name: "Panna Cotta",
    description: "Vanilla bean panna cotta with seasonal berry compote",
    price: 9,
    badges: [],
  },
  {
    itemId: "cannoli",
    category: "desserts",
    name: "Cannoli",
    description: "Crispy shell filled with sweet ricotta, chocolate chips, pistachios",
    price: 8,
    badges: [],
  },
  {
    itemId: "italian-soda",
    category: "desserts",
    name: "Italian Soda",
    description: "Sparkling water with your choice of house-made fruit syrup",
    price: 5,
    badges: [],
  },
  {
    itemId: "espresso",
    category: "desserts",
    name: "Espresso",
    description: "Double shot of our house blend, imported from Naples",
    price: 4,
    badges: [],
  },
  {
    itemId: "bottled-water",
    category: "desserts",
    name: "Bottled Water",
    description: "Chilled bottled spring water",
    price: 3,
    badges: [],
  },
];

module.exports = menuItems;
