export const navLinks = [
  { href: "#home", label: "Home" },
  { href: "#menu", label: "Menu" },
  { href: "#about", label: "About" },
  { href: "#contact", label: "Contact" },
];

export const features = [
  {
    icon: "bi-fire",
    title: "Wood-Fired",
    text: "Every pizza baked at 900 degrees in our imported Italian brick oven for that perfect char.",
  },
  {
    icon: "bi-flower1",
    title: "Fresh Ingredients",
    text: "San Marzano tomatoes, buffalo mozzarella, and herbs picked daily from our garden.",
  },
  {
    icon: "bi-trophy",
    title: "Award Winning",
    text: "Voted Best Pizza in the City five years running by New York Food Magazine.",
  },
];

export const galleryItems = [
  {
    title: "Our Signature Margherita",
    src: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=1200&q=80",
    thumb: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=200&q=60",
    alt: "Margherita pizza",
  },
  {
    title: "BBQ Chicken",
    src: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1200&q=80",
    thumb: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=200&q=60",
    alt: "Pizza topped with chicken",
  },
  {
    title: "Our Dining Room",
    src: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&q=80",
    thumb: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=200&q=60",
    alt: "Restaurant dining room",
  },
  {
    title: "Fresh Caprese Salad",
    src: "https://images.unsplash.com/photo-1595587870672-c79b47875c6a?q=80&w=1800&auto=format&fit=crop",
    thumb: "https://images.unsplash.com/photo-1529543544282-ea669407fca3?w=200&q=60",
    alt: "Caprese salad",
  },
  {
    title: "Homemade Tiramisu",
    src: "https://staticcookist.akamaized.net/wp-content/uploads/sites/22/2024/09/THUMB-VIDEO-2_rev1-56.jpeg",
    thumb: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=200&q=60",
    alt: "Tiramisu dessert",
  },
  {
    title: "Classic Pepperoni",
    src: "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=1200&q=80",
    thumb: "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=200&q=60",
    alt: "Pizza dough being tossed",
  },
];

export const menuCategories = [
  { id: "classic", label: "Classic Pizzas" },
  { id: "specialty", label: "Specialty Pizzas" },
  { id: "starters", label: "Appetizers & Salads" },
  { id: "desserts", label: "Desserts & Drinks" },
];

export const menuItems = [
  {
    id: "margherita",
    category: "classic",
    name: "Margherita",
    description: "San Marzano tomato sauce, fresh mozzarella, basil, extra virgin olive oil",
    price: 14,
    badges: ["Popular", "Vegetarian"],
  },
  {
    id: "pepperoni",
    category: "classic",
    name: "Pepperoni",
    description: "Tomato sauce, mozzarella, spicy pepperoni, oregano",
    price: 16,
    badges: ["Popular"],
  },
  {
    id: "quattro-formaggi",
    category: "classic",
    name: "Quattro Formaggi",
    description: "Mozzarella, gorgonzola, parmesan, fontina cheese blend",
    price: 17,
    badges: ["Vegetarian"],
  },
  {
    id: "marinara",
    category: "classic",
    name: "Marinara",
    description: "San Marzano tomatoes, garlic, oregano, extra virgin olive oil - no cheese",
    price: 12,
    badges: ["Vegetarian"],
  },
  {
    id: "capricciosa",
    category: "classic",
    name: "Capricciosa",
    description: "Tomato, mozzarella, ham, mushrooms, artichokes, olives",
    price: 18,
    badges: [],
  },
  {
    id: "truffle-mushroom",
    category: "specialty",
    name: "Truffle Mushroom",
    description: "Wild mushroom medley, truffle cream, mozzarella, arugula, shaved parmesan",
    price: 22,
    badges: ["Popular", "Vegetarian"],
  },
  {
    id: "prosciutto-rucola",
    category: "specialty",
    name: "Prosciutto e Rucola",
    description: "Tomato, mozzarella, Prosciutto di Parma, arugula, parmesan shavings",
    price: 20,
    badges: [],
  },
  {
    id: "diavola",
    category: "specialty",
    name: "Diavola",
    description: "Spicy salami, roasted peppers, tomato sauce, mozzarella, chili flakes",
    price: 18,
    badges: [],
  },
  {
    id: "bbq-chicken",
    category: "specialty",
    name: "BBQ Chicken",
    description: "Grilled chicken, BBQ sauce, red onion, cilantro, smoked gouda",
    price: 19,
    badges: [],
  },
  {
    id: "mediterranean",
    category: "specialty",
    name: "Mediterranean",
    description: "Sun-dried tomatoes, olives, feta, artichokes, roasted peppers, pesto drizzle",
    price: 19,
    badges: ["Vegetarian"],
  },
  {
    id: "bruschetta-trio",
    category: "starters",
    name: "Bruschetta Trio",
    description: "Classic tomato-basil, mushroom truffle, and ricotta-honey on toasted ciabatta",
    price: 12,
    badges: [],
  },
  {
    id: "caprese-salad",
    category: "starters",
    name: "Caprese Salad",
    description: "Fresh buffalo mozzarella, vine tomatoes, basil, balsamic reduction",
    price: 13,
    badges: ["Vegetarian"],
  },
  {
    id: "arancini",
    category: "starters",
    name: "Arancini",
    description: "Crispy risotto balls filled with mozzarella, served with marinara",
    price: 11,
    badges: [],
  },
  {
    id: "caesar-salad",
    category: "starters",
    name: "Caesar Salad",
    description: "Romaine hearts, house-made caesar dressing, croutons, parmesan",
    price: 11,
    badges: [],
  },
  {
    id: "tiramisu",
    category: "desserts",
    name: "Tiramisu",
    description: "Classic espresso-soaked ladyfingers with mascarpone cream",
    price: 10,
    badges: ["Popular"],
  },
  {
    id: "panna-cotta",
    category: "desserts",
    name: "Panna Cotta",
    description: "Vanilla bean panna cotta with seasonal berry compote",
    price: 9,
    badges: [],
  },
  {
    id: "cannoli",
    category: "desserts",
    name: "Cannoli",
    description: "Crispy shell filled with sweet ricotta, chocolate chips, pistachios",
    price: 8,
    badges: [],
  },
  {
    id: "italian-soda",
    category: "desserts",
    name: "Italian Soda",
    description: "Sparkling water with your choice of house-made fruit syrup",
    price: 5,
    badges: [],
  },
  {
    id: "espresso",
    category: "desserts",
    name: "Espresso",
    description: "Double shot of our house blend, imported from Naples",
    price: 4,
    badges: [],
  },
  {
    id: "bottled-water",
    category: "desserts",
    name: "Bottled Water",
    description: "Chilled bottled spring water",
    price: 3,
    badges: [],
  },
];
